---
title: Prediction of Readmission for Diabetic Patients
author: Anran Yao, Mingrui Li, Wenjing Li
date: "December 16, 2020"
output:
  pdf_document: default
  html_document: default
  rmarkdown::pdf_document:
    fig_caption: yes
    includes: null
    latex_engine: lualatex
---

## 1.Introduction
Diabetes is a chronic disease that affects millions of people around the world, and managing diabetes can be a complex and challenging task. One important aspect of diabetes management is the prevention of hospital readmissions, as frequent readmissions can be costly$^{[1]}$ and may negatively impact patient outcomes$^{[2]}$. In this study, we aimed to develop a prediction model for readmission rates for diabetic patients using a dataset from Kaggle. We used several prediction methods, including logistic regression, naive bayesian, random forest, and K-nearest-neighbor, and evaluated their performance using AUC, ROC, and confusion matrix.

## 2.Methods

### 2.1 Study Population  
The dataset we used in this study was provided by Kaggle which contained information on diabetic patients who were hospitalized. The data range from 1999 to 2008 included a total of 101,766 samples and 50 variables, with each sample representing an unique observation of admission. The dataset included demographic and physical features for medications, number of inpatient visits and diagnoses. 


### 2.2 Data cleaning  
Before analysis, the dataset was cleaned and preprocessed to remove any missing or irrelevant data. Variables with significant imbalance in sample proportions (e.g. one of the categories accounts for >99%) were excluded. Variables with more than 40% missingness were excluded such as weight, payer code and medical specialty. We also deleted rows containing missing values in race. After exclusion, 30 variables were left.

### 2.3 Variables  
The outcome of this study is readmitted, a categorical variable that indicates days to inpatient readmission. The outcome has 3 values, “<30” or “>30” if the patient was readmitted in less or more than 30 days and “No” for no record of readmission. We convert the outcome to binary by considering “No” as 0, readmitted as 1 no matter less or more than 30 days.  
The variables diagnose 1, diagnose 2 and diagnose 3 were merged to find the 6 most frequent ICD-9 codes and considered as a new variable. For those codes with decimal points like 250.01, it belongs to the same group as 250.   
The following variables were added in this study: number_inpatient, which reflects the number of inpatient visits of the patient in the year preceding the encounter; number_enmergency, which represents the number of emergency visits; num_medications, which indicates the number of distinct generic names administered during the encounter; diabetesMed, to demonstrate if there was any diabetic medication prescribed; age, which grouped in 10-year intervals.
	
### 2.4 Statistical analysis  
To predict readmission rates, we used four different prediction methods: logistic regression, naive bayesian, random forest, and K-nearest-neighbor. Logistic regression is a statistical method that is commonly used for binary classification tasks, such as predicting the likelihood of a patient being readmitted. Naive Bayesian is a machine learning method that uses probability theory to make predictions based on the features of the data. Random forest is a machine learning method that uses decision trees to make predictions based on the features of the data. K-nearest-neighbor is a machine learning method that makes predictions based on the similarity of the data to previously seen examples.  
To evaluate the performance of the prediction models, we used three evaluation metrics: AUC, ROC, and confusion matrix. AUC (area under the curve) is a measure of the performance of a binary classification model, with a value of 1 indicating perfect performance and a value of 0.5 indicating random performance. ROC (receiver operating characteristic) is a plot of the true positive rate against the false positive rate, and is used to evaluate the performance of a binary classification model. Confusion matrix is a table that shows the number of true positive, true negative, false positive, and false negative predictions made by a classification model.

## 3. Methodology
To predict readmission rates, we used four different prediction methods: logistic regression, naive bayesian, random forest, and K-nearest-neighbor. 

### 3.1 Logistic Regression  
Logistic regression is a statistical method that is used to predict a binary outcome, such as whether an event will occur or not. It is based on the principle of linear regression, but the dependent variable is transformed into a binary outcome using a logistic function. Logistic regression is a linear method, which means that it makes predictions based on a linear combination of the input features. 

### 3.2 Naive Bayesian  
Naive Bayesian is a probabilistic machine learning method that is based on the principle of Bayesian probability. It is called "naive" because it assumes that all of the features in the dataset are independent of one another, which is not always the case in real-world data. Despite this assumption, naive Bayesian algorithms can still be very effective at making predictions in many situations.

### 3.3  Decision Tree  
Decision tree is a machine learning algorithm that is used to make predictions based on a tree-like model of decisions. It works by dividing the input data into smaller and smaller subsets based on the values of the input features. At each step, the algorithm chooses the feature that provides the most information about the target variable, and splits the data accordingly. The resulting tree can then be used to make predictions by following the path through the tree that leads to the most likely outcome.

### 3.4 Random Forest  
Random forest is an ensemble learning method that is used to make predictions based on the collective input of a group of decision trees. It works by creating a large number of decision trees using random subsets of the input data, and then averaging the predictions made by each tree. This can help to reduce the overall variance of the predictions, and can lead to improved predictive performance, which explains why the random forest has the best predictive performance on this study.





**Missing Data Imputations:** Due to the pattern of missing values and their abundance, we decided to impute the missing values before analysis. To avoid the potential loss of data, we decided to impute the missing data in our predictors of interest using package *Hmisc*:$^{[8]}$ each COVID-related predictor was imputed five times. Imputed values were then stored in five different datasets, respectively. We fitted models on each of the datasets and then used the “pool” function from package *mice* to combine the estimates from the models that fit on these datasets.$^{[9]}$ The R-squared values for predicting non-missing values for each variable are from around 10% to 30%.


### Results



Table 2. Unadjusted analysis for mental health outcomes with COVID-related predictors

#### Unadjusted Analysis 

As shown in Table 2, virtual medical appointment due to COVID is a significant predictor for all the mental health outcomes (p<0.05). There are also some other significant patterns. People who were unable to receive medical care because of the COVID pandemic are 1.17 times more likely to have anxiety, compared to those who could receive medical care despite COVID (95% CI [1.03, 1.34], p<0.05) (Table 2). In addition, people ever tested for COVID are 1.15 times more likely to take medication for anxiety (95% CI [1.03, 1.29], p<0.05). 

#### Adjusted Analysis

After adding demographic variables, the following demographic variables show a somewhat consistent relationship across the six mental health outcomes. Minority racial groups including Asian, Black, and Hispanics are less likely to have mental health issues compared to Non-Hispanic White. People older than 45 years old are also less likely to suffer from these psychological problems, except for taking medication for depression, compared to those aged 18-44. Males are less likely to suffer from anxiety or depression and take medication for these conditions compared to females.

**Took medicine for mental health problems:**
People who had virtual medical appointments due to COVID are 1.77 times more likely to take medicine for mental health (95% CI [1.33, 2.34], p<0.05). People who are 45 years or older are less likely to take medicine for mental health, compared to the younger people (p<0.05). In addition, minority racial groups, such as Asian, Black, and Hispanic, are less likely to take medicine for mental health problems compared to White (p<0.05).

**Received counseling for mental health:**
People who had virtual medical appointments due to COVID are 2.09 times more likely to receive mental health counseling from health professionals (95% CI [1.85, 2.37], p<0.05). Interestingly, males are 0.63 times less likely to receive such therapy (95% CI [0.57, 0.70], p<0.05). Additionally, people who have college or higher degrees are 1.38 times more likely to receive mental health counseling (95% CI [1.23, 1.56], p<0.05).

**Ever had depression:**
People who had virtual medical appointments due to COVID are 1.58 times more likely to have depression (95% CI [1.45, 1.72], p<0.05). Males are 0.5 times less likely to suffer from depression (95% CI [0.47, 0.55], p<0.05). People who have college or higher degrees are 0.88 times less likely to have depression (95% CI [0.81, 0.96], p<0.05).

**Take medication for depression:**
People ever tested for COVID are 1.14 times more likely to take medication for depression (95% CI [1.01, 1.30], p<0.05). People who had virtual medical appointments due to COVID are 1.85 times more likely to take depression medicine (95% CI [1.67, 2.05], p<0.05). Males are 0.43 times less likely to take such medication (95% CI [0.38, 0.47], p<0.05). It is worth noticing that age behaves differently for this particular outcome, compared to other outcomes. People who are between 45 and 64 years old are 1.3 times more likely to take medication for depression (95% CI [1.16, 1.45], p<0.05).




Figure 3. Forest Plots of Odds Ratios in Weighted Logistic Regressions [reference levels are not shown in the plot: for all the binary variables (without an equal sign in the covariate name), the reference is *no*; the reference group is *18-44* for *age*, *female* for *sex*, *high school or below* for *education*, and *Non-Hispanic Whites* for *race/ethnicity* (abbreviated as *race* in the plots)]

 
**Ever had Anxiety:**
People who were unable to receive medical care from health professionals due to the coronavirus pandemic are 1.17 times more likely to have anxiety (95% CI [1.02, 1.35], p<0.05). In addition, people who had virtual medical appointments due to COVID are 1.65 times more likely to have anxiety (95% CI [1.50, 1.82], p<0.05). Males are 0.49 times less likely to suffer from anxiety (95% CI [0.45, 0.53], p<0.05). People who have college or higher degrees are 0.87 times less likely to have anxiety (95% CI [0.79, 0.95], p<0.05). Noticeably, Native Americans/Alaska natives (AIAN) are 1.49 times more likely to have anxiety, compared to White (95% CI [1.10, 2.00], p<0.05).

**Take medication for anxiety:**
People ever tested for COVID are 1.16 times more likely to take medication for anxiety (95% CI [1.03, 1.30], p<0.05). In addition, people who had virtual medical appointments due to COVID are 1.88 times more likely to take anxiety medicine (95% CI [1.65, 2.13], p<0.05). Males are 0.42 times less likely to take such medication (95% CI [0.39, 0.47], p<0.05).

### Conclusions and Discusssions

In conclusion, people who had COVID and who did not have COVID were equally likely to have anxiety and depression, take medicine for anxiety and depression, and receive psychological counseling. Some of the subgroups of people who had tested COVID were less likely to show anxiety and depression, but more likely to take medicine for anxiety and depression. As the hospital burden increased due to rising cases, people who did not receive medical care other than COVID might have anxiety feelings. People who had virtual medical appointments in 2020 were more likely to have anxiety and depression, take medicine for anxiety and depression, and receive psychological counseling.

Regarding demographics features: compared to people aged 18 to 44, people aged 45 to 64 were more likely to take medication for depression, but were less likely to have anxiety and depression, and receive psychological counseling. People aged 65+ were less likely to have anxiety and depression, and receive psychological counseling. People with college or higher degrees were more likely to receive psychological counseling but less likely to have anxiety and depression. Compared to females, males would be less likely to have anxiety and depression, take medicine for anxiety and depression, and have psychological counseling. Native Americans/Alaska natives would be more likely to have anxiety compared to White people. Compared to Asian, Black, and Hispanic, White people were more likely to have anxiety and depression, take medicine for anxiety and depression, and receive psychological counseling. To interpret all these trends, we need to take economics instability during the pandemic into consideration. The unemployment rates increased, and people were worried about the family budget, meanwhile inflation rates rose.

Some of the results were slightly deviated from our expectations. For example, people aged 45 to 64 were less likely to have depression but took more medication for depression than people who were younger. The participants answered “Yes” to the “ever had depression” and “ever had anxiety” questions only if they had been told so by a doctor or health professionals which included experience before COVID. The outcome variables “take medication for depression” and “take medication for anxiety” are indications for current status in 2020. Therefore, the reason that they seemingly took medicine without a history of mental illness could be that the participants showed trends of anxiety or depression, but the illness was not severe, so the doctors recommended some medication to relieve the stress. Moreover, if people had received medical treatment or appointments, they would have fewer mental issues. This was different from the result of variable “virtual medical appointments”. We suspected that the variable also included online psychological counseling. For race, we were surprised that Non Hispanic Whites were more vulnerable to mental illness than racial groups who had less healthcare access during COVID, for example, Black. This could be due to that Non Hispanic Whites cared more about mental illness than other racial groups.

Regarding the limitations of our study, the dataset is susceptible to recall bias and information bias. For the imputation of the missing values, we had a relatively low R-squared, and thus the imputed data might not be accurate. Moreover, we suspected that the covariates we chose had the issues of multicollinearity. As another future step, we could also consider add interaction terms among the predictors in the multinomial logistic regression model.

Overall, people did face mental illness during the COVID-19 pandemic due to fear of contracting the virus, lack of access to healthcare, and economical instability. Our study understood the impact of COVID-19 on mental illness. With the result of the study, healthcare professionals can better guide people on mental health problems during and after the pandemic.

### References    
[1] Joynt, K. E., & Jha, A. K. (2012). Thirty-day readmissions—truth and consequences. *N Engl j med*, 366(15), 1366-1369.  

[2] Rubin, D. J. (2015). Hospital readmission of patients with diabetes. *Current diabetes reports*, 15(4), 1-9.

3) ~ 9) Run citation('srvyr'), citation('ggplot2'), citation('gtsummary'), citation('naniar'), citation('finalfit'), citation('Hmisc'), citation('mice')  in R to get more details.
Footer
