---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Prediction of Readmission for Diabetic Patients
This is a project to predict the possibility of readmission for diabetic patients based on their demographic and physical features of patients, medications, number of certain medical record and diagnoses.
<!-- badges: start -->

<!-- badges: end -->
##Recource
Dataset from 


##Repository Details
**R**
-   `dataprocessing.R` Read and clean the raw data, recode for diagnoses and medical. Code used for descriptive analysis.
-   `predictionmodels.R` Code for spliting data and predictive model, including logistic regression, naive bayesian, decision tree and random forest.
-   `resultsandplots.R` Code for model comparison using ROC, AUC and confusion matrix, showinig results for the four prediction methods.
**Report**

##Attribution
Dataset in this project was from Kaggle [Diabetic Patients' Re-admission Prediction](https://www.kaggle.com/datasets/saurabhtayal/diabetic-patients-readmission-prediction/code), attributing to Saurabh Tayal.
